version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/input-server
  - source: /scripts
    destination: /home/ubuntu/scripts
file_exists_behavior: OVERWRITE

permissions:
  - object: /home/ubuntu/scripts
    pattern: "**"
    owner: ubuntu
    group: www-data
    mode: 755

hooks:
  AfterInstall:
    - location: scripts/init.sh
      timeout: 300
      runas: ubuntu

  ApplicationStart:
    - location: scripts/deploy.sh
      timeout: 300
      runas: ubuntu