"""init db

Revision ID: 001757654bf4
Revises: 
Create Date: 2024-10-28 17:03:08.944983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '001757654bf4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assistant_id',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assistant_id', sa.String(length=100), nullable=False, comment='Assistant ID for chatGPT api'),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assistant_id_assistant_id'), 'assistant_id', ['assistant_id'], unique=False)
    op.create_index(op.f('ix_assistant_id_id'), 'assistant_id', ['id'], unique=False)
    op.create_table('presets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parameter', sa.JSON(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('api_type', sa.Enum('T2I', 'I2I', name='apitype'), nullable=False),
    sa.Column('assistant_id_id', sa.Integer(), nullable=True, comment='Assistant ID for chatGPT api'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assistant_id_id'], ['assistant_id.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_presets_id'), 'presets', ['id'], unique=False)
    op.create_table('call',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('input_prompt', sa.String(length=1000), nullable=False, comment='입력 프롬프트'),
    sa.Column('preset_id', sa.Integer(), nullable=False),
    sa.Column('prompt', sa.String(length=1000), nullable=False, comment='생성 프롬프트'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['preset_id'], ['presets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_call_id'), 'call', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_call_id'), table_name='call')
    op.drop_table('call')
    op.drop_index(op.f('ix_presets_id'), table_name='presets')
    op.drop_table('presets')
    op.drop_index(op.f('ix_assistant_id_id'), table_name='assistant_id')
    op.drop_index(op.f('ix_assistant_id_assistant_id'), table_name='assistant_id')
    op.drop_table('assistant_id')
    # ### end Alembic commands ###
