"""init new db

Revision ID: ee91f47aa14d
Revises: 
Create Date: 2025-02-27 01:28:18.838215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee91f47aa14d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assistant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assistant_id', sa.String(length=100), nullable=False, comment='Assistant ID for chatGPT api'),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assistant_assistant_id'), 'assistant', ['assistant_id'], unique=False)
    op.create_index(op.f('ix_assistant_id'), 'assistant', ['id'], unique=False)
    op.create_table('preset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parameter', sa.JSON(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('api_type', sa.Enum('T2I', 'I2I', name='apitype'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_preset_id'), 'preset', ['id'], unique=False)
    op.create_table('generation_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('preset_id', sa.Integer(), nullable=False),
    sa.Column('assistant_id', sa.Integer(), nullable=False),
    sa.Column('cron_rule', sa.String(length=100), nullable=False),
    sa.Column('next_run_time', sa.DateTime(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assistant_id'], ['assistant.id'], ),
    sa.ForeignKeyConstraint(['preset_id'], ['preset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generation_settings_assistant_id'), 'generation_settings', ['assistant_id'], unique=False)
    op.create_index(op.f('ix_generation_settings_cron_rule'), 'generation_settings', ['cron_rule'], unique=False)
    op.create_index(op.f('ix_generation_settings_id'), 'generation_settings', ['id'], unique=False)
    op.create_index(op.f('ix_generation_settings_next_run_time'), 'generation_settings', ['next_run_time'], unique=False)
    op.create_index(op.f('ix_generation_settings_preset_id'), 'generation_settings', ['preset_id'], unique=False)
    op.create_table('history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prompt', sa.String(length=2000), nullable=True),
    sa.Column('generation_setting_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('is_success', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['generation_setting_id'], ['generation_settings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_history_generation_setting_id'), 'history', ['generation_setting_id'], unique=False)
    op.create_index(op.f('ix_history_id'), 'history', ['id'], unique=False)
    op.create_index(op.f('ix_history_image_url'), 'history', ['image_url'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_history_image_url'), table_name='history')
    op.drop_index(op.f('ix_history_id'), table_name='history')
    op.drop_index(op.f('ix_history_generation_setting_id'), table_name='history')
    op.drop_table('history')
    op.drop_index(op.f('ix_generation_settings_preset_id'), table_name='generation_settings')
    op.drop_index(op.f('ix_generation_settings_next_run_time'), table_name='generation_settings')
    op.drop_index(op.f('ix_generation_settings_id'), table_name='generation_settings')
    op.drop_index(op.f('ix_generation_settings_cron_rule'), table_name='generation_settings')
    op.drop_index(op.f('ix_generation_settings_assistant_id'), table_name='generation_settings')
    op.drop_table('generation_settings')
    op.drop_index(op.f('ix_preset_id'), table_name='preset')
    op.drop_table('preset')
    op.drop_index(op.f('ix_assistant_id'), table_name='assistant')
    op.drop_index(op.f('ix_assistant_assistant_id'), table_name='assistant')
    op.drop_table('assistant')
    # ### end Alembic commands ###
